version: "3.9"

volumes:
  geo-db-data:
  prometheus-data:
  grafana-data:

networks:
  geocluster:

services:
  ### PostgreSQL
  db:
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    volumes:
      - geo-db-data:/var/lib/postgresql
      - ${BUILD_WEB_XML}:/settings/web.xml
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - FORCE_SSL=FALSE
    ports:
      - ${POSTGRES_PORT}:5432
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U docker -d gis"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - geocluster
    labels: 
      org.label-schema.group: "database"

  ### Active-MQ
  geobroker:
    build:
      context: ./scripts/docker/build/activemq
      dockerfile: Dockerfile
    environment:
      - JAVA_HOME=/opt/java/openjdk
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - SSL_MODE=FALSE
      - ACTIVEMQ_SERVER_URI=tcp://0.0.0.0:61616?maximumConnections=1000&wireFormat.maxFrameSize=104857600&jms.useAsyncSend=false&transport.daemon=true
      - ACTIVEMQ_SERVER_DISCOVERYURI=multicast://default
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8161:8161
      - 61616:61616
    healthcheck:
      test: netstat -ltn | grep -c ":61616"
      interval: 60s
      timeout: 15s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    networks:
      - geocluster
    labels: 
      org.label-schema.group: "broker"

  ### Geoserver-1
  gs-node1:
    image: geobeyond/geoserver:2.20.6
    volumes:
      - ${GEOSERVER_DATA_MNT}:${GEOSERVER_DATA_DIR}
      - ${GEOSERVER_CACHE_MNT}:${GEOSERVER_CACHE_DIR}
    ports:
      - "8081:8080"
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR} 
      - GEOWEBCACHE_CACHE_DIR=${GEOSERVER_CACHE_DIR}
      - RECREATE_DATADIR=FALSE
      - BROKER_URL=tcp://0.0.0.0:61616
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - READONLY=disabled
      - CLUSTER_DURABILITY=false
      - CLUSTERING=True
      - TOGGLE_MASTER=true
      - TOGGLE_SLAVE=true
      - EMBEDDED_BROKER=disabled
      - CLUSTER_CONNECTION_RETRY_COUNT=10
      - CLUSTER_CONNECTION_MAX_WAIT=500
      - DB_BACKEND=POSTGRES
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - SSL_MODE=allow
      - RANDOMSTRING=23bd87cfa327d47e-node1
      - INSTANCE_STRING=ac3bcba2fa7d989678a01ef4facc4173010cd8b40d2e5f5a8d18d5f863ca976f-node1
      - SAMPLE_DATA=false
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      geobroker:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/geoserver/web || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 100s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    networks:
      - geocluster
    labels: 
      org.label-schema.group: "geoserver"

  ### Geoserver-2
  gs-node2:
    image: geobeyond/geoserver:2.20.6
    volumes:
      - ${GEOSERVER_DATA_MNT}:${GEOSERVER_DATA_DIR}
      - ${GEOSERVER_CACHE_MNT}:${GEOSERVER_CACHE_DIR}
    ports:
      - "8082:8080"
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR} 
      - GEOWEBCACHE_CACHE_DIR=${GEOSERVER_CACHE_DIR}
      - RECREATE_DATADIR=FALSE
      - BROKER_URL=tcp://0.0.0.0:61616
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - READONLY=disabled
      - CLUSTER_DURABILITY=false
      - CLUSTERING=True
      - TOGGLE_MASTER=true
      - TOGGLE_SLAVE=true
      - EMBEDDED_BROKER=disabled
      - CLUSTER_CONNECTION_RETRY_COUNT=10
      - CLUSTER_CONNECTION_MAX_WAIT=500
      - DB_BACKEND=POSTGRES
      - HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=gis
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - SSL_MODE=allow
      - RANDOMSTRING=23bd87cfa327d47e-node2
      - INSTANCE_STRING=ac3bcba2fa7d989678a01ef4facc4173010cd8b40d2e5f5a8d18d5f863ca976f-node2
      - SAMPLE_DATA=false
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      geobroker:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/geoserver/web || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 100s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    networks:
      - geocluster
    labels:
      org.label-schema.group: "geoserver"

  ### Load balancer
  caddy:
    image: caddy:2.7.6-alpine
    build:
      context: ./scripts/docker/build/caddy
      dockerfile: Dockerfile
    volumes:
      - ./scripts/docker/build/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 8600:8600
    healthcheck:
      test: curl -s -o /dev/null -w "%{http_code}" http://localhost:8600 | grep -E "^(200|302)$$" || exit 1
      interval: 1m
      retries: 5  
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
        reservations:
          memory: 64M
          cpus: '0.1'
    depends_on:
      gs-node1:
        condition: service_healthy
      gs-node2:
        condition: service_healthy
      geobroker:
        condition: service_healthy
    networks:
      - geocluster
    labels:
      org.label-schema.group: "reverse-proxy"

  ### Metric
  prometheus:
    image: prom/prometheus:v2.48.1
    build:
      context: ./scripts/docker/build/prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    user: "65534:65534"
    volumes: 
      - ./scripts/docker/build/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - geocluster
    labels: 
      org.label-schema.group: "monitoring"

  ### Web Based UI Visualization of Metrics
  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    ports:
      - 3000:3000
    user: "472:0"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - geocluster
    labels:
      org.label-schema.group: "monitoring"

  ### Host Linux Machine Metrics exporter for prometheus
  ### GUIDE: https://github.com/DoTheEvo/selfhosted-apps-docker/blob/master/prometheus_grafana_loki/
  nodeexporter:
    image: prom/node-exporter:v1.5.0
    container_name: nodeexporter
    hostname: nodeexporter
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - "9100"
    networks:
      - geocluster
    labels:
      org.label-schema.group: "monitoring"
  
  ### Docker container exporter for prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    hostname: cadvisor
    expose:
      - "8080"
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - '--housekeeping_interval=30s'
      - '--docker_only=true'
      - '--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,hugetlb,referenced_memory,cpu_topology,resctrl'
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'
    networks:
      - geocluster
    labels:
      org.label-schema.group: "monitoring"
    depends_on: 
      - caddy
